name: bus_route
description: Bus route

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  flare_splash_screen: ^3.0.1
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  firebase_database: ^4.1.1
  connectivity: ^2.0.1
  google_maps_flutter: ^1.1.1
  outline_material_icons: ^0.1.1
  geolocator: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


  assets:
     - images/



  fonts:
     - family: Monteserrat
       fonts:
         - asset: fonts/Montserrat-Regular.ttf
     - family: Roboto
       fonts:
         - asset: fonts/Roboto-Regular.ttf
     - family: Roboto-Bold
       fonts:
         - asset: fonts/Roboto-Bold.ttf




